### ISSUE TITLE
Validar que la dosis de una medicina esté entre 1 y 10

### ISSUE THREAD

**Issue by facularrauri** [facularrauri/vetsoft#3]
**Como** usuario del sistema de veterinaria,

**quiero** que el sistema valide que la dosis de una medicina ingresada esté en un rango válido (entre 1 y 10)

**para** garantizar que las dosis registradas sean adecuadas y realistas, evitando errores en la administración de medicamentos.

**Comment by pilita-acosta** [comment]
Close with #7

**Comment by lucasmartinez22** [comment]
Cerrada la tarea, se procede a mergear a main. Tests aprobados
